import { defineConfig, type OxlintConfig } from "oxlint";

import plugin from "./index.ts";

const utilfirstRules = Object.fromEntries(
  Object.keys(plugin.rules).map((ruleName) => [
    `utilfirst/${ruleName}`,
    "error" as const,
  ]),
);

/**
 * Shared Oxlint policy for TypeScript and browser React repositories. The
 * OxlintConfig annotation keeps the emitted declaration on Oxlint's own type, so
 * consumers with exactOptionalPropertyTypes can pass it to `extends`.
 */
export const oxlintBaseConfig: OxlintConfig = defineConfig({
  categories: {
    correctness: "error",
    pedantic: "error",
    perf: "error",
    suspicious: "error",
  },
  env: {
    "builtin": true,
    "es2024": true,
    "shared-node-browser": true,
  },
  jsPlugins: [
    {
      name: "utilfirst",
      specifier: "@utilfirst/eslint-plugin",
    },
  ],
  options: {
    reportUnusedDisableDirectives: "error",
    typeAware: true,
    typeCheck: true,
  },
  overrides: [
    {
      // Config modules run under Node regardless of the repository runtime.
      files: ["*.config.{js,cjs,mjs,ts,mts}", "app.config.ts"],
      env: {
        node: true,
      },
    },
    {
      // Plain JavaScript modules carry no type information, so type-aware
      // rules only produce noise there.
      files: ["**/*.{js,cjs,mjs}"],
      env: {
        node: true,
      },
      rules: {
        "no-undef": "error",
        "typescript/await-thenable": "off",
        "typescript/consistent-type-exports": "off",
        "typescript/dot-notation": "off",
        "typescript/no-array-delete": "off",
        "typescript/no-base-to-string": "off",
        "typescript/no-deprecated": "off",
        "typescript/no-duplicate-type-constituents": "off",
        "typescript/no-floating-promises": "off",
        "typescript/no-for-in-array": "off",
        "typescript/no-implied-eval": "off",
        "typescript/no-meaningless-void-operator": "off",
        "typescript/no-misused-spread": "off",
        "typescript/no-mixed-enums": "off",
        "typescript/no-redundant-type-constituents": "off",
        "typescript/no-unnecessary-boolean-literal-compare": "off",
        "typescript/no-unnecessary-condition": "off",
        "typescript/no-unnecessary-qualifier": "off",
        "typescript/no-unnecessary-template-expression": "off",
        "typescript/no-unnecessary-type-arguments": "off",
        "typescript/no-unnecessary-type-assertion": "off",
        "typescript/no-unnecessary-type-conversion": "off",
        "typescript/no-unnecessary-type-parameters": "off",
        "typescript/no-unsafe-argument": "off",
        "typescript/no-unsafe-assignment": "off",
        "typescript/no-unsafe-call": "off",
        "typescript/no-unsafe-enum-comparison": "off",
        "typescript/no-unsafe-member-access": "off",
        "typescript/no-unsafe-return": "off",
        "typescript/no-unsafe-type-assertion": "off",
        "typescript/no-unsafe-unary-minus": "off",
        "typescript/no-useless-default-assignment": "off",
        "typescript/non-nullable-type-assertion-style": "off",
        "typescript/only-throw-error": "off",
        "typescript/prefer-find": "off",
        "typescript/prefer-includes": "off",
        "typescript/prefer-promise-reject-errors": "off",
        "typescript/prefer-readonly": "off",
        "typescript/prefer-reduce-type-parameter": "off",
        "typescript/prefer-regexp-exec": "off",
        "typescript/prefer-return-this-type": "off",
        "typescript/prefer-string-starts-ends-with": "off",
        "typescript/promise-function-async": "off",
        "typescript/related-getter-setter-pairs": "off",
        "typescript/require-array-sort-compare": "off",
        "typescript/restrict-plus-operands": "off",
        "typescript/return-await": "off",
        "typescript/strict-boolean-expressions": "off",
        "typescript/strict-void-return": "off",
        "typescript/switch-exhaustiveness-check": "off",
        "typescript/unbound-method": "off",
        "typescript/use-unknown-in-catch-callback-variable": "off",
      },
    },
    {
      // CommonJS config files exist only where a tool requires them.
      files: ["**/*.cjs"],
      rules: {
        "import/no-commonjs": "off",
        "typescript/no-require-imports": "off",
      },
    },
    {
      files: ["**/*.{ts,tsx,mts,cts}"],
      rules: {
        // Type-aware analysis owns these base correctness checks for TypeScript.
        "constructor-super": "off",
        "getter-return": "off",
        "no-class-assign": "off",
        "no-const-assign": "off",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-new-native-nonconstructor": "off",
        "no-obj-calls": "off",
        "no-setter-return": "off",
        "no-this-before-super": "off",
        "no-unused-vars": "off",
      },
    },
    {
      files: ["**/*.test.{ts,tsx,mts,cts}"],
      rules: {
        // Async fakes may preserve a promise boundary without performing work.
        "no-empty-function": ["error", { allow: ["asyncFunctions"] }],
        "typescript/require-await": "off",
      },
    },
  ],
  plugins: [
    "eslint",
    "import",
    "jsdoc",
    "jsx-a11y",
    "oxc",
    "promise",
    "react",
    "typescript",
    "unicorn",
    "vitest",
  ],
  rules: {
    ...utilfirstRules,
    "arrow-body-style": ["error", "as-needed"],
    "curly": "error",
    "default-case-last": "error",
    "default-param-last": "error",
    "eqeqeq": ["error", "smart"],
    "grouped-accessor-pairs": "error",
    "guard-for-in": "error",
    "import/export": "error",
    "import/first": "error",
    "import/max-dependencies": "off",
    "import/no-duplicates": "error",
    "import/no-amd": "error",
    "import/no-anonymous-default-export": "error",
    "import/no-commonjs": "error",
    "import/no-cycle": "error",
    "import/no-dynamic-require": "error",
    "import/no-mutable-exports": "error",
    "import/no-named-default": "error",
    // Stylesheets, polyfills, and registration modules use side-effect imports.
    "import/no-unassigned-import": "off",
    "import/no-webpack-loader-syntax": "error",
    "jsdoc/require-param": "off",
    "jsdoc/require-returns": "off",
    "logical-assignment-operators": "error",
    // Ownership and extraction decisions depend on behavior, not line counts.
    "max-lines": "off",
    "max-lines-per-function": "off",
    // Retry, pagination, and ordered transition loops may require serial awaits.
    "no-await-in-loop": "off",
    "no-alert": "error",
    // Bitwise syntax is valid for masks, binary formats, and low-level transforms.
    "no-bitwise": "off",
    // Logging policy depends on boundary ownership and payload sensitivity.
    "no-console": "off",
    "no-div-regex": "error",
    "no-empty": "error",
    "no-empty-function": "error",
    "no-extra-label": "error",
    "no-implicit-coercion": "error",
    "no-implicit-globals": "error",
    "no-label-var": "error",
    "no-labels": "error",
    "no-lone-blocks": "error",
    "no-multi-assign": "error",
    "no-new-func": "error",
    // Negative guard clauses are valid when they keep the main path terminal.
    "no-negated-condition": "off",
    "no-nested-ternary": "error",
    "no-param-reassign": "error",
    "no-proto": "error",
    "no-regex-spaces": "error",
    "no-return-assign": "error",
    "no-script-url": "error",
    "no-sequences": "error",
    "no-template-curly-in-string": "error",
    // External protocols and generated shapes may own leading-underscore names.
    "no-underscore-dangle": "off",
    "no-useless-assignment": "error",
    "no-warning-comments": "off",
    "object-shorthand": "error",
    "operator-assignment": "error",
    "oxc/no-map-spread": "off",
    "prefer-arrow-callback": ["error", { allowNamedFunctions: true }],
    "prefer-const": "error",
    "prefer-exponentiation-operator": "error",
    "prefer-numeric-literals": "error",
    "prefer-object-has-own": "error",
    "prefer-object-spread": "error",
    "prefer-regex-literals": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    "promise/catch-or-return": "error",
    "promise/no-nesting": "error",
    "promise/no-return-wrap": "error",
    "promise/no-return-in-finally": "error",
    "promise/param-names": "error",
    // The category-enabled exhaustive-deps rule retains missing-dependency checks.
    "react/exhaustive-effect-dependencies": "off",
    "react/function-component-definition": "error",
    "react/hook-use-state": "error",
    "react/jsx-boolean-value": "error",
    "react/jsx-curly-brace-presence": "error",
    "react/jsx-fragments": "error",
    "react/jsx-pascal-case": "error",
    "react/no-clone-element": "error",
    // Sink safety depends on the value's trust boundary, not the JSX syntax.
    "react/no-danger": "off",
    "react/no-react-children": "error",
    // React escapes text nodes; typographic source characters are safe here.
    "react/no-unescaped-entities": "off",
    "react/no-unknown-property": "error",
    // Render-prop APIs intentionally accept caller-owned component functions.
    "react/no-unstable-nested-components": ["error", { allowAsProps: true }],
    "react/prefer-function-component": "error",
    // Compiler optimization bailouts are not runtime or maintainability defects.
    "react/preserve-manual-memoization": "off",
    "react/react-in-jsx-scope": "off",
    // Compiler ref analysis currently reports ordinary ref props and callbacks.
    "react/refs": "off",
    "react/self-closing-comp": "error",
    // External-system and hydration effects legitimately synchronize local state.
    "react/set-state-in-effect": "off",
    // Type-aware require-await owns TypeScript functions without duplicate reports.
    "require-await": "off",
    "typescript/adjacent-overload-signatures": "error",
    "typescript/array-type": "error",
    "typescript/ban-tslint-comment": "error",
    "typescript/class-literal-property-style": "error",
    "typescript/consistent-generic-constructors": "error",
    "typescript/consistent-indexed-object-style": "error",
    "typescript/consistent-type-assertions": "error",
    "typescript/consistent-type-definitions": ["error", "type"],
    "typescript/consistent-type-imports": [
      "error",
      { fixStyle: "separate-type-imports", prefer: "type-imports" },
    ],
    "typescript/consistent-return": "off",
    "typescript/consistent-type-exports": "error",
    "typescript/dot-notation": "error",
    "typescript/method-signature-style": ["error", "property"],
    "typescript/no-dynamic-delete": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-inferrable-types": "error",
    "typescript/no-import-type-side-effects": "error",
    "typescript/no-invalid-void-type": "error",
    "typescript/no-namespace": "error",
    "typescript/no-non-null-assertion": "error",
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-unnecessary-condition": [
      "error",
      { allowConstantLoopConditions: true },
    ],
    "typescript/no-unnecessary-qualifier": "error",
    "typescript/non-nullable-type-assertion-style": "error",
    "typescript/prefer-find": "error",
    "typescript/prefer-for-of": "error",
    "typescript/prefer-function-type": "error",
    "typescript/prefer-literal-enum-member": "error",
    "typescript/prefer-optional-chain": "error",
    "typescript/prefer-readonly": "error",
    // Readonly parameter pressure can reject valid local mutation before aliasing.
    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/prefer-reduce-type-parameter": "error",
    "typescript/prefer-regexp-exec": "error",
    "typescript/prefer-return-this-type": "error",
    "typescript/prefer-string-starts-ends-with": "error",
    "typescript/restrict-plus-operands": [
      "error",
      {
        allowAny: false,
        allowBoolean: false,
        allowNullish: false,
        allowNumberAndString: false,
        allowRegExp: false,
      },
    ],
    "typescript/return-await": ["error", "error-handling-correctness-only"],
    "typescript/strict-boolean-expressions": [
      "error",
      {
        allowAny: false,
        allowNullableBoolean: true,
        allowNullableEnum: false,
        allowNullableNumber: false,
        allowNullableObject: true,
        allowNullableString: false,
        allowNumber: false,
        allowString: false,
      },
    ],
    "typescript/unified-signatures": "error",
    "typescript/use-unknown-in-catch-callback-variable": "error",
    "unicode-bom": ["error", "never"],
    "unicorn/catch-error-name": "error",
    "unicorn/consistent-date-clone": "error",
    "unicorn/consistent-template-literal-escape": "error",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/custom-error-definition": "error",
    "unicorn/error-message": "error",
    "unicorn/explicit-timer-delay": "error",
    "unicorn/no-abusive-eslint-disable": "error",
    "unicorn/no-anonymous-default-export": "error",
    "unicorn/no-array-method-this-argument": "error",
    "unicorn/no-await-expression-member": "error",
    "unicorn/no-console-spaces": "error",
    "unicorn/no-document-cookie": "error",
    "unicorn/no-length-as-slice-end": "error",
    "unicorn/no-magic-array-flat-depth": "error",
    "unicorn/no-negated-condition": "off",
    "unicorn/no-process-exit": "error",
    "unicorn/no-unreadable-array-destructuring": "error",
    "unicorn/no-useless-collection-argument": "error",
    "unicorn/no-zero-fractions": "error",
    // Explicit undefined can communicate an optional boundary or reset operation.
    "unicorn/no-useless-undefined": "off",
    "unicorn/numeric-separators-style": [
      "error",
      {
        number: {
          groupLength: 3,
          minimumDigits: 4,
          onlyIfContainsSeparator: true,
        },
      },
    ],
    "unicorn/prefer-array-index-of": "error",
    "unicorn/prefer-bigint-literals": "error",
    "unicorn/prefer-class-fields": "error",
    "unicorn/prefer-classlist-toggle": "error",
    "unicorn/prefer-default-parameters": "error",
    "unicorn/prefer-dom-node-text-content": "error",
    "unicorn/prefer-includes": "error",
    "unicorn/prefer-keyboard-event-key": "error",
    "unicorn/prefer-modern-dom-apis": "error",
    "unicorn/prefer-modern-math-apis": "error",
    "unicorn/prefer-module": "error",
    "unicorn/prefer-negative-index": "error",
    "unicorn/prefer-node-protocol": "error",
    "unicorn/prefer-number-properties": "error",
    "unicorn/prefer-object-from-entries": "error",
    "unicorn/prefer-optional-catch-binding": "error",
    "unicorn/prefer-response-static-json": "error",
    "unicorn/prefer-string-trim-start-end": "error",
    "unicorn/prefer-structured-clone": "error",
    "unicorn/relative-url-style": "error",
    "unicorn/require-array-join-separator": "error",
    "unicorn/require-module-attributes": "error",
    "unicorn/switch-case-braces": "error",
    "unicorn/switch-case-break-position": "error",
    "unicorn/text-encoding-identifier-case": "error",
    "unicorn/throw-new-error": "error",
    // Module-scope awaits hide import-time I/O before callers can intervene.
    "unicorn/prefer-top-level-await": "off",
    "vitest/expect-expect": "off",
    "vitest/no-conditional-in-test": "off",
    "vitest/no-alias-methods": "error",
    "vitest/no-duplicate-hooks": "error",
    "vitest/no-identical-title": "error",
    "vitest/no-import-node-test": "error",
    "vitest/no-test-prefixes": "error",
    "vitest/prefer-called-exactly-once-with": "error",
    "vitest/prefer-comparison-matcher": "error",
    "vitest/prefer-equality-matcher": "error",
    "vitest/prefer-expect-type-of": "error",
    "vitest/prefer-hooks-in-order": "error",
    "vitest/prefer-hooks-on-top": "error",
    "vitest/prefer-import-in-mock": "error",
    "vitest/prefer-importing-vitest-globals": "error",
    "vitest/prefer-mock-promise-shorthand": "error",
    "vitest/prefer-mock-return-shorthand": "error",
    "vitest/prefer-spy-on": "error",
    "vitest/prefer-strict-boolean-matchers": "error",
    "vitest/prefer-strict-equal": "error",
    "vitest/prefer-to-be": "error",
    "vitest/prefer-to-be-object": "error",
    "vitest/prefer-to-contain": "error",
    "vitest/prefer-to-have-length": "error",
    "vitest/prefer-todo": "error",
  },
  settings: {
    react: {
      version: "19",
    },
  },
});
