import type { OxlintConfig } from "oxlint";

import plugin from "./index.ts";

const utilfirstRules = Object.fromEntries(
  Object.keys(plugin.rules).map((ruleName) => [
    `utilfirst/${ruleName}`,
    "error" as const,
  ]),
);

/** Shared Oxlint policy for TypeScript and React repositories. */
export const oxlintBaseConfig = {
  categories: {
    correctness: "error",
    pedantic: "error",
    perf: "error",
    suspicious: "error",
  },
  env: {
    "builtin": true,
    "es2024": true,
    "shared-node-browser": true,
  },
  jsPlugins: [
    {
      name: "utilfirst",
      specifier: "@utilfirst/eslint-plugin",
    },
  ],
  options: {
    typeAware: true,
    typeCheck: true,
  },
  overrides: [
    {
      files: ["**/*.{ts,tsx,mts,cts}"],
      rules: {
        "constructor-super": "off",
        "getter-return": "off",
        "no-class-assign": "off",
        "no-const-assign": "off",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-new-native-nonconstructor": "off",
        "no-obj-calls": "off",
        "no-setter-return": "off",
        "no-this-before-super": "off",
        "no-unused-vars": "off",
      },
    },
    {
      files: ["**/*.test.{ts,tsx,mts,cts}"],
      rules: {
        "typescript/require-await": "off",
      },
    },
  ],
  plugins: [
    "eslint",
    "import",
    "oxc",
    "promise",
    "react",
    "typescript",
    "unicorn",
    "vitest",
  ],
  rules: {
    ...utilfirstRules,
    "arrow-body-style": ["error", "as-needed"],
    "curly": "error",
    "eqeqeq": ["error", "smart"],
    "import/export": "error",
    "import/first": "error",
    "import/max-dependencies": "off",
    "import/no-duplicates": "error",
    "import/no-unassigned-import": "off",
    "max-lines": "off",
    "max-lines-per-function": "off",
    "no-await-in-loop": "off",
    "no-negated-condition": "off",
    "no-underscore-dangle": "off",
    "no-useless-assignment": "error",
    "object-shorthand": "error",
    "prefer-arrow-callback": ["error", { allowNamedFunctions: true }],
    "prefer-const": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "promise/catch-or-return": "error",
    "promise/no-nesting": "error",
    "promise/no-return-in-finally": "error",
    "promise/no-return-wrap": "error",
    "promise/param-names": "error",
    "react/function-component-definition": "error",
    "react/hook-use-state": "error",
    "react/jsx-curly-brace-presence": "error",
    "react/no-unstable-nested-components": ["error", { allowAsProps: true }],
    "react/no-unescaped-entities": "off",
    "react/react-in-jsx-scope": "off",
    "require-await": "off",
    "typescript/adjacent-overload-signatures": "error",
    "typescript/array-type": "error",
    "typescript/ban-tslint-comment": "error",
    "typescript/class-literal-property-style": "error",
    "typescript/consistent-generic-constructors": "error",
    "typescript/consistent-indexed-object-style": "error",
    "typescript/consistent-type-assertions": "error",
    "typescript/consistent-type-definitions": ["error", "type"],
    "typescript/consistent-type-imports": [
      "error",
      { fixStyle: "inline-type-imports", prefer: "type-imports" },
    ],
    "typescript/consistent-return": "off",
    "typescript/dot-notation": "error",
    "typescript/no-dynamic-delete": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-inferrable-types": "error",
    "typescript/no-invalid-void-type": "error",
    "typescript/no-namespace": "error",
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-unnecessary-condition": [
      "error",
      { allowConstantLoopConditions: true },
    ],
    "typescript/non-nullable-type-assertion-style": "error",
    "typescript/prefer-find": "error",
    "typescript/prefer-for-of": "error",
    "typescript/prefer-function-type": "error",
    "typescript/prefer-literal-enum-member": "error",
    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/prefer-reduce-type-parameter": "error",
    "typescript/prefer-regexp-exec": "error",
    "typescript/prefer-return-this-type": "error",
    "typescript/prefer-string-starts-ends-with": "error",
    "typescript/restrict-plus-operands": [
      "error",
      {
        allowAny: false,
        allowBoolean: false,
        allowNullish: false,
        allowNumberAndString: false,
        allowRegExp: false,
      },
    ],
    "typescript/return-await": ["error", "error-handling-correctness-only"],
    "typescript/unified-signatures": "error",
    "typescript/use-unknown-in-catch-callback-variable": "error",
    "unicode-bom": ["error", "never"],
    "unicorn/no-negated-condition": "off",
    "unicorn/no-useless-undefined": "off",
    "unicorn/prefer-top-level-await": "off",
    "vitest/no-conditional-in-test": "off",
  },
  settings: {
    react: {
      version: "19",
    },
  },
} satisfies OxlintConfig;
